// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultSubnet() {
  return window['go']['main']['App']['GetDefaultSubnet']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProbeIP(arg1) {
  return window['go']['main']['App']['ProbeIP'](arg1);
}

export function ScanSubnet(arg1, arg2) {
  return window['go']['main']['App']['ScanSubnet'](arg1, arg2);
}
